# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35f12804abc13d0122eb0cd11e835d483eefcde082ca70adf4277d42ee1ac9597a7c662c492e1f3739fffaa7bd8e12549ea35cae581ae3f12a5647a996f1e6c2

test:
  secret_key_base: 38d8a23358925612bd5afc1a1160440cd619dc4ecb421ec54836283c51799c13b7d0bcf9dc8deef82536799fa9a04ccf050f6314f6d281cfd43152042ac20959

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
